services:
  - mongodb

env:
  - MONGODB_PORT_27017_TCP_ADDR=127.0.0.1

language: java

jdk:
  - oraclejdk8

before_script:
  - sleep 15

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls
