/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '10/04/16 10:04 AM' with Gradle 2.12
 *
 * @author hongkailiu, @date 10/04/16 10:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
